### ISSUE TITLE
Fur Cloaks not providing warmth

### ISSUE THREAD

**Issue by Mixeddd** [Guitarninja2/septimus#47]
Fur cloaks aren't providing warmth. Band aid solution is installing older version of survival control panel and using the "Cloaks give warmth" option.

**Comment by Guitarninja2** [comment]
Interestingly the cloaks do have survival warmth set but it seems sunhelm doesn't use those values so I may need to give them frostfall warmth values heh.

**Comment by rsrogers4** [comment]
On a similar topic, maybe the Bandolier items shouldn't provide warmth? GuitarNinja, I'd be happy to help figure out and suggest the correct SunHelm parameters for cloaks, bandoliers, and the SimonMagus Apothecary foods if you want some assistance.

**Comment by Guitarninja2** [comment]
Yeah agreed the bandolier stuff definitely shouldn't. If you know how to use xEdit and can figure out the clothes items that'd be great. I'm pretty busy bug fixing for the full release.

**Comment by rsrogers4** [comment]
I am pretty sure the bandolier items provide warmth because they have the `ArmorMaterialLeather` keyword, and I don't know if there would be negative effects of removing this.

The cloaks have both the `Survival_ArmorWarm` and `FrostfallsCloakFur` keywords. From what I can tell, @Mixeddd's original suggestion to use [Survival Control Panel](https://www.nexusmods.com/skyrimspecialedition/mods/41891) may be the only way to enable cloak warmth.

It seems like the SimonMagus Apothecary foods already have Survival Mode effects through the patch. I will have to look more closely in game to see what foods were a "surprise" to SunHelm. Sometimes it seems like eating a raw carrot restores more hunger than a fancy cooked meal which doesn't seem right, but I need to do more research.

**Comment by Guitarninja2** [comment]
This should be fixed now with the move to creation club survival instead of sunhelm
